// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function PatternMatchingDemoError(Props) {
  var result = Props.result;
  var status = Props.status;
  if (status) {
    return React.createElement("p", undefined, "Unavailable.");
  } else if (typeof result === "number") {
    return React.createElement("p", undefined, "Loading...");
  } else if (result.tag) {
    var list = result[0];
    if (list.length !== 0) {
      return React.createElement("ul", undefined, Belt_Array.map(list, (function (item) {
                        return React.createElement("li", undefined, item);
                      })));
    } else {
      return React.createElement("p", undefined, "List is empty!");
    }
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "_none_",
            1,
            -1
          ]
        ];
  }
}

var make = PatternMatchingDemoError;

exports.make = make;
/* react Not a pure module */
