// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

var wrapper = Css.style(/* :: */[
      Css.height(Css.pct(100)),
      /* :: */[
        Css.width(Css.pct(100)),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* wrapper */wrapper];

function VideoBackground(Props) {
  var src = Props.src;
  return React.createElement("video", {
              className: wrapper,
              autoPlay: true,
              loop: true,
              muted: true
            }, React.createElement("source", {
                  src: src,
                  type: "video/mp4"
                }));
}

var make = VideoBackground;

var $$default = VideoBackground;

exports.Styles = Styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* wrapper Not a pure module */
